version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey8888
      - ALLOWED_HOSTS=127.0.0.1,34.105.118.4

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static_data:
